</strong> <p style="text-align:center"><b> <br>

<font color="#00E5FF">
╔═══〔 PROX BOTZ 〕═══╗
</font><br>

<font color="#FFD700">
✦ Welcome To Premium Server ✦
</font><br>

<font color="#FF4C4C">❖ No Torrent</font> 
<font color="#FFFFFF">| ❖ No Hacking</font> 
<font color="#00FF7F">| ❖ No Mining</font><br>

<font color="#00E5FF">
➤ @ProXBotz
</font><br>

<font color="#FFFFFF">
Owner : Satyajeet Kumar
</font><br>

<font color="#00E5FF">
╚════════════════════╝
</font><br>
